[package]
name = "auction"
version = "0.1.0"
authors = ["Vladimir Kharitonov <khvv@yandex-team.ru>"]

[dependencies]
exonum = { version = "0.9.0", path = "../exonum/exonum" }
serde = "1.0.0"
serde_json = "1.0.0"
serde_derive = "1.0.0"
failure = "0.1.1"
lazy_static = "1.1.0"
